# encoding: utf-8


class Table(object):
    def config_db(self,pkg):
        tbl =  pkg.table('shipdoc',pkey='id',name_long='Shipdoc',name_plural='Shipdocs',caption_field='id')
        self.sysFields(tbl)
        tbl.column('vessel_name',size='22',name_short='!![en]vessel name').relation('pfda.imbarcazione.id',relation_name='imbarcazione_pfda', mode='foreignkey', onDelete='raise')
        tbl.column('vessel_details',size='22',name_short='!![en]vessel details').relation('vessel_details.id',relation_name='dettagli_nave', mode='foreignkey', onDelete='raise')
        tbl.column('ad_place',size='22',name_short='ad place').relation('unlocode.place.id',relation_name='anch_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('ad_date',dtype='D',name_short='ad date')
        tbl.column('ad_date_exp',dtype='D',name_short='ad date exp')
        tbl.column('adovt_place',size='22',name_short='ad ovt place').relation('unlocode.place.id',relation_name='anchovt_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('adovt_date',dtype='D',name_short='ad ovt date')
        tbl.column('adovt_date_exp',dtype='D',name_short='ad ovt date exp')
        tbl.column('saf_eq_pass_place', size='22', name_short='saf eq pass place').relation('unlocode.place.id',relation_name='saf_eq_pass_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('saf_eq_pass_date', dtype='D', name_short='saf eq pass date') 
        tbl.column('saf_eq_pass_exp', dtype='D',name_short='saf eq pass exp')
        tbl.column('saf_eq_pass_place_last', size='22', name_short='saf eq pass place last').relation('unlocode.place.id',relation_name='saf_eq_pass_place_lv_un', mode='foreignkey', onDelete='raise')         
        tbl.column('saf_eq_pass_place_lastdate', dtype='D', name_short='saf eq pass last visit')
        tbl.column('saf_eq_place', size='22', name_short='saf eq pass place').relation('unlocode.place.id',relation_name='saf_eq_pass_un', mode='foreignkey', onDelete='raise')
        tbl.column('saf_eq_date', dtype='D', name_short='saf eq pass date') 
        tbl.column('saf_eq_exp', dtype='D',name_short='saf eq pass exp')
        tbl.column('saf_eq_place_last', size='22', name_short='saf eq pass place last').relation('unlocode.place.id',relation_name='saf_eq_pass_lv_un', mode='foreignkey', onDelete='raise')         
        tbl.column('saf_eq_place_lastdate', dtype='D', name_short='saf eq pass last visit')
        tbl.column('saf_rt_place', size='22', name_short='saf rt place').relation('unlocode.place.id',relation_name='saf_rt_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('saf_rt_date', dtype='D', name_short='saf rt date') 
        tbl.column('saf_rt_exp', dtype='D',name_short='saf rt exp')
        tbl.column('saf_rt_place_last', size='22', name_short='saf rt place last').relation('unlocode.place.id',relation_name='saf_rt_place_lv_un', mode='foreignkey', onDelete='raise')         
        tbl.column('saf_rt_place_lastdate', dtype='D', name_short='saf rt last visit')
        tbl.column('loadline_place', size='22', name_short='loadline place').relation('unlocode.place.id',relation_name='loadline_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('loadline_date', dtype='D', name_short='loadline date') 
        tbl.column('loadline_exp', dtype='D',name_short='loadline exp')
        tbl.column('loadline_place_last', size='22', name_short='loadline place last').relation('unlocode.place.id',relation_name='loadline_place_lv_un', mode='foreignkey', onDelete='raise')         
        tbl.column('loadline_place_lastdate', dtype='D', name_short='loadline last visit')
        tbl.column('sanitation_place', size='22', name_short='sanitation place').relation('unlocode.place.id',relation_name='sanitation_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('sanitation_date', dtype='D', name_short='sanitation date') 
        tbl.column('sanitation_exp', dtype='D',name_short='sanitation exp')
        tbl.column('issc_place', size='22', name_short='issc place').relation('unlocode.place.id',relation_name='issc_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('issc_date', dtype='D', name_short='issc date') 
        tbl.column('issc_exp', dtype='D',name_short='issc exp')
        tbl.column('issc_place_lastdate', dtype='D', name_short='issc last visit')
        tbl.column('doc_place', size='22', name_short='doc place').relation('unlocode.place.id',relation_name='doc_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('doc_date', dtype='D', name_short='doc date') 
        tbl.column('doc_exp', dtype='D',name_short='doc exp')
        tbl.column('doc_place_lastdate', dtype='D', name_short='doc last visit')
        tbl.column('smc_place', size='22', name_short='smc place').relation('unlocode.place.id',relation_name='smc_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('smc_date', dtype='D', name_short='smc date') 
        tbl.column('smc_exp', dtype='D',name_short='smc exp')
        tbl.column('smc_place_lastdate', dtype='D', name_short='smc last visit')
        tbl.column('iopp_place', size='22', name_short='iopp place').relation('unlocode.place.id',relation_name='iopp_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('iopp_date', dtype='D', name_short='iopp date') 
        tbl.column('iopp_exp', dtype='D',name_short='iopp exp')
        tbl.column('iopp_place_last', size='22', name_short='iopp place last').relation('unlocode.place.id',relation_name='iopp_place_lv_un', mode='foreignkey', onDelete='raise')         
        tbl.column('iopp_place_lastdate', dtype='D', name_short='iopp last visit')
        tbl.column('pmou_place', size='22', name_short='pmou place').relation('unlocode.place.id',relation_name='pmou_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('pmou_date', dtype='D', name_short='pmou date') 
        tbl.column('msm_place', size='22', name_short='msm place').relation('unlocode.place.id',relation_name='msm_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('msm_date', dtype='D', name_short='msm date') 
        tbl.column('msm_exp', dtype='D',name_short='msm exp')
        tbl.column('msm_place_lastdate', dtype='D', name_short='msm last visit')
        tbl.column('class_place', size='22', name_short='smc place').relation('unlocode.place.id',relation_name='class_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('class_date', dtype='D', name_short='class date') 
        tbl.column('class_exp', dtype='D',name_short='class exp')
        tbl.column('noteclass', name_short='note class')
        tbl.column('ido_place', size='22', name_short='ido place').relation('unlocode.place.id',relation_name='ido_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('ido_date', dtype='D', name_short='ido date') 
        tbl.column('ido_exp', dtype='D',name_short='ido exp')
        tbl.column('noteido', name_short='note ido')
        tbl.column('ts_place', size='22', name_short='ts place').relation('unlocode.place.id',relation_name='ts_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('ts_date', dtype='D', name_short='ts date') 
        tbl.column('ts_exp', dtype='D',name_short='ts exp')
        tbl.column('notets', name_short='note ts')
        tbl.column('sb_place', size='22', name_short='sb place').relation('unlocode.place.id',relation_name='sb_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('sb_date', dtype='D', name_short='sb date') 
        tbl.column('sb_exp', dtype='D',name_short='sb exp')
        tbl.column('notesb', name_short='note sb')
        tbl.column('ass_place', size='22', name_short='ass place').relation('unlocode.place.id',relation_name='ass_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('ass_date', dtype='D', name_short='ass date') 
        tbl.column('ass_exp', dtype='D',name_short='ass exp')
        tbl.column('noteass', name_short='note ass')
        tbl.column('ruolo_num', size=':10', name_short='ruolo n.')
        tbl.column('ruolo_serie', size=':2', name_short='ruolo serie')
        tbl.column('ruolo_place', size='22', name_short='ruolo place').relation('unlocode.place.id',relation_name='ruolo_place_un', mode='foreignkey', onDelete='raise')
        tbl.column('ruolo_date', dtype='D', name_short='ruolo date') 
        tbl.column('noteruolo', name_short='note ruolo')
        tbl.column('speed_dich', name_short='speed dich')
        tbl.column('speed_eff', name_short='speed eff')
        tbl.aliasColumn('gt','@vessel_name.gt',name_long='!![en]GT')     
        tbl.aliasColumn('nt','@vessel_name.nt',name_long='!![en]NT')    
        tbl.aliasColumn('bandiera','@vessel_name.bandiera',name_long='!![en]Flag')    
        tbl.aliasColumn('loa','@vessel_name.loa',name_long='!![en]LOA')    
        tbl.aliasColumn('imo','@vessel_name.imo',name_long='IMO')    
        
      

